Repository square/okhttp, pull requests merged in 2021-07, with the labels that each got.

#6751 Fix tests for android
  android-test/build.gradle
  okhttp-dnsoverhttps/build.gradle
  okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.java
Labels: android

#6758 Android CI variants
  .github/workflows/build.yml
Labels: android

#6755 Android dependency upgrade
  android-test/build.gradle
  android-test/settings.gradle
  regression-test/build.gradle
  regression-test/settings.gradle
Labels: android

#6761 Clean Android Regression Test
  .github/workflows/build.yml
  regression-test/build.gradle
  regression-test/src/androidTest/java/okhttp/regression/IssueReproductionTest.java
Labels: android-regression

#6736 Added Dispatched.clear() method for testing
  mockwebserver/src/main/kotlin/mockwebserver3/QueueDispatcher.kt
  mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java
Labels: enhancement

#6660 Run native image tests in CI
  .github/workflows/build.yml
  native-image-tests/build.gradle
  native-image-tests/src/main/kotlin/okhttp3/TestRegistration.kt
  native-image-tests/src/main/resources/META-INF/native-image/okhttp/nit/resource-config.json
  native-image-tests/src/main/resources/testlist.txt
  okcurl/build.gradle
  okhttp/src/test/java/okhttp3/HttpUrlTest.java
  okhttp/src/test/java/okhttp3/WebPlatformUrlTest.java
  okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt
Labels: graal

#6787 Fix lagging graal dependency
  okhttp/build.gradle
Labels: graal

#6750 Android 30 CloseGuard
  okhttp/src/main/kotlin/okhttp3/internal/platform/Android10Platform.kt
  okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt
  okhttp/src/main/kotlin/okhttp3/internal/platform/android/CloseGuard.kt
Labels: android

#6788 Bump AGP to 7.0.0
  .github/workflows/build.yml
  android-test/build.gradle
  build.gradle
  regression-test/build.gradle
Labels: android

#6795 Remove older TLS versions on JDK 291+
  okhttp/src/test/java/okhttp3/JSSETest.kt
Labels: jdk8

#6794 Activate TLSv1.3 on JDK 8
  okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
Labels: jdk8

#6779 Work around Graal Issue
  okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
  okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
Labels: graal

#6793 Optimize dependencies in android modules
  android-test/build.gradle
  buildSrc/src/main/kotlin/deps.kt
  regression-test/build.gradle
Labels: android, android-regression

#6797 Convert android modules' gradle to kts
  android-test/build.gradle
  android-test/build.gradle.kts
  regression-test/build.gradle
  regression-test/build.gradle.kts
Labels: android, android-regression

#6798 Convert part of gradle to kts
  build.gradle
  native-image-tests/build.gradle
  native-image-tests/build.gradle.kts
  okcurl/build.gradle
  okcurl/build.gradle.kts
  okhttp-testing-support/build.gradle.kts
Labels: android, android-regression, graal

#6799 Extract dependencies to `Dependencies`
  build.gradle
  buildSrc/src/main/kotlin/deps.kt
  mockwebserver-junit5/build.gradle.kts
  native-image-tests/build.gradle.kts
  okcurl/build.gradle.kts
  samples/compare/build.gradle.kts
Labels: graal
