Repository square/okhttp, pull requests merged in 2021-11, with the labels that each got.

#6792 Extend Proguard Rules
  okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
Labels: android

#6921 Enforce max intermediates in BasicCertificateChainCleaner
  okhttp/src/main/kotlin/okhttp3/internal/tls/BasicCertificateChainCleaner.kt
  okhttp/src/test/java/okhttp3/CertificateChainCleanerTest.java
  okhttp/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
Labels: graal, conscrypt, providers

#6862 Allow Custom SSLSocketFactory without ALPN support
  android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/DelegatingSSLSession.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/DelegatingSSLSocket.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/DelegatingSSLSocketFactory.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/DelegatingServerSocketFactory.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/DelegatingSocketFactory.kt
  okhttp/src/main/kotlin/okhttp3/internal/platform/android/Android10SocketAdapter.kt
  okhttp/src/test/java/okhttp3/DelegatingSSLSession.java
  okhttp/src/test/java/okhttp3/DelegatingSSLSocket.java
  okhttp/src/test/java/okhttp3/DelegatingSSLSocketFactory.java
  okhttp/src/test/java/okhttp3/DelegatingServerSocketFactory.java
  okhttp/src/test/java/okhttp3/DelegatingSocketFactory.java
  okhttp/src/test/java/okhttp3/FallbackTestClientSocketFactory.java
  okhttp/src/test/java/okhttp3/internal/SocketRecorder.java
  okhttp/src/test/java/okhttp3/internal/http/ThreadInterruptTest.java
Labels: android

#6934 Fix module name after kts switch
  android-test/build.gradle.kts
  native-image-tests/build.gradle.kts
Labels: android, graal

#6937 Remove suppression check that can never pass.
  okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Labels: jdk8

#6936 Fix for junit5 executor with nativeImage
  native-image-tests/src/main/kotlin/okhttp3/RunTests.kt
Labels: graal

#6938 Update dependencies
  buildSrc/src/main/kotlin/deps.kt
  native-image-tests/build.gradle.kts
  okcurl/build.gradle.kts
Labels: android, graal, jdk17
