Repository square/okhttp, pull requests merged in 2021-08, with the labels that each got.

#6808 Allow test passing on JDK 8
  okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
Labels: jdk8

#6809 Allow ClientAuthTest changes on JDK8 after security updates.
  okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Labels: jdk8

#6807 Kapt picocliCompiler in okcurl module
  okcurl/build.gradle.kts
Labels: graal

#6810 Avoid task logger flakes due to shared logger.
  okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskLogger.kt
  okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
  okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
  okhttp/src/test/java/okhttp3/TestLogHandler.java
  okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
  okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
Labels: jdk8

#6806 Update dependencies
  build.gradle
  buildSrc/src/main/kotlin/deps.kt
Labels: android, graal, jdk8

#6818 Rewrite Http2 test to be less flaky
  okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Labels: android, jdk8, tests

#6819 Rewrite Http2 connectionNotReusedAfterShutdown test to be less flaky
  okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Labels: jdk8

#6822 Refine code
  mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/RecordedRequest.kt
  mockwebserver-junit4/src/test/java/mockwebserver3/junit4/MockWebServerRuleTest.kt
  mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
  okcurl/src/main/kotlin/okhttp3/curl/Main.kt
  okhttp-brotli/src/main/kotlin/okhttp3/brotli/BrotliInterceptor.kt
  okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/FakeDns.kt
  okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
  okhttp/src/main/kotlin/okhttp3/Handshake.kt
  okhttp/src/main/kotlin/okhttp3/internal/NativeImageTestsAccessors.kt
  okhttp/src/main/kotlin/okhttp3/internal/http/StatusLine.kt
  okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
  okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
  okhttp/src/test/java/okhttp3/HeadersKotlinTest.kt
  okhttp/src/test/java/okhttp3/KotlinDeprecationErrorTest.kt
  okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
  okhttp/src/test/java/okhttp3/OpenJSSETest.kt
  okhttp/src/test/java/okhttp3/RecordingExecutor.kt
  okhttp/src/test/java/okhttp3/SocketChannelTest.kt
  okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt
  okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
  samples/guide/src/main/java/okhttp3/recipes/kt/YubikeyClientAuth.kt
Labels: android, graal
