Repository square/okhttp, pull requests merged in 2023-01, with the labels that each got.

#7600 Track API changes in native-image-tests
  native-image-tests/src/main/kotlin/okhttp3/SampleTest.kt
Labels: graal

#7602 Get more TLS stuff passing on BouncyCastle
  mockwebserver-deprecated/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
  mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
  okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
  okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
  okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
  okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.kt
  okhttp/src/jvmTest/java/okhttp3/CacheCorruptionTest.kt
  okhttp/src/jvmTest/java/okhttp3/CacheTest.java
  okhttp/src/jvmTest/java/okhttp3/CallHandshakeTest.kt
  okhttp/src/jvmTest/java/okhttp3/CallKotlinTest.kt
  okhttp/src/jvmTest/java/okhttp3/CallTest.kt
  okhttp/src/jvmTest/java/okhttp3/ConnectionReuseTest.kt
  okhttp/src/jvmTest/java/okhttp3/DuplexTest.java
  okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
  okhttp/src/jvmTest/java/okhttp3/InsecureForHostTest.kt
  okhttp/src/jvmTest/java/okhttp3/JSSETest.kt
  okhttp/src/jvmTest/java/okhttp3/RouteFailureTest.kt
  okhttp/src/jvmTest/java/okhttp3/ServerTruncatesRequestTest.kt
  okhttp/src/jvmTest/java/okhttp3/SessionReuseTest.kt
  okhttp/src/jvmTest/java/okhttp3/SocketChannelTest.kt
  okhttp/src/jvmTest/java/okhttp3/URLConnectionTest.kt
  okhttp/src/jvmTest/java/okhttp3/internal/http/CancelTest.kt
  okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
  okhttp/src/jvmTest/java/okhttp3/internal/tls/HostnameVerifierTest.kt
  okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
  samples/compare/src/test/kotlin/okhttp3/compare/OkHttpClientTest.kt
Labels: providers

#7613 Add CI tests for Loom
  .github/workflows/build.yml
  build.gradle.kts
  okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
  okhttp/src/jvmTest/java/okhttp3/LoomTest.kt
Labels: loom

#7615 Make tests conscrypt safe
  .github/workflows/build.yml
  okhttp/src/jvmTest/java/okhttp3/ConnectionListenerTest.kt
Labels: conscrypt

#7614 Add a CI build for JDK 19
  .github/workflows/build.yml
  samples/compare/src/test/kotlin/okhttp3/compare/JavaHttpClientTest.kt
Labels: jdkversions

#7618 Fix JavaHttpClientTest tests on JDK 19
  samples/compare/src/test/kotlin/okhttp3/compare/JavaHttpClientTest.kt
Labels: jdkversions

#7607 Avoid InetAddress.getCanonicalHostName().
  mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
  okhttp-android/src/androidTest/kotlin/okhttp3/android/AndroidAsyncDnsTest.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
  okhttp-tls/README.md
  okhttp-tls/src/main/kotlin/okhttp3/tls/internal/TlsUtil.kt
  okhttp/src/jvmTest/java/okhttp3/OpenJSSETest.kt
  samples/guide/src/main/java/okhttp3/recipes/HttpsServer.java
Labels: windows

#7367 Loom Support
  gradle.properties
  okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
  okhttp/api/okhttp.api
  okhttp/src/jvmMain/kotlin/okhttp3/Cache.kt
  okhttp/src/jvmMain/kotlin/okhttp3/ConnectionPool.kt
  okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/-UtilJvm.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/internal.kt
  okhttp/src/jvmTest/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
  settings.gradle.kts
Labels: loom

#7597 Confirm we send SNI server names on the JDK9 Platform
  mockwebserver/api/mockwebserver3.api
  mockwebserver/src/main/kotlin/mockwebserver3/RecordedRequest.kt
  mockwebserver/src/test/java/mockwebserver3/MockResponseSniTest.kt
  okhttp-tls/src/main/kotlin/okhttp3/tls/internal/TlsUtil.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/Android10Platform.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/AndroidPlatform.kt
  okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/Platform.kt
Labels: android, graal, conscrypt, windows, providers

#7630 Make tolerant of JDK 19 quirks
  okhttp/src/jvmTest/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
Labels: jdkversions

#7648 [4.x] Cherry pick: fix DoH error when using ip address as hostname
  okhttp/src/main/kotlin/okhttp3/internal/connection/RouteSelector.kt
  okhttp/src/test/java/okhttp3/EventListenerTest.java
Labels: bug
