Repository square/okhttp, pull requests merged in 2023-05, with the labels that each got.

#7715 Add some IDN tests
  okhttp/build.gradle.kts
  okhttp/src/jvmTest/java/okhttp3/WebPlatformToAsciiData.kt
  okhttp/src/jvmTest/java/okhttp3/WebPlatformToAsciiTest.kt
  okhttp/src/jvmTest/java/okhttp3/WebPlatformUrlTestData.kt
  okhttp/src/jvmTest/resources/web-platform-test-toascii.json
Labels: jdkversions

#7862 Fix android test
  android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
Labels: android

#7861 Gradle 8.1
  gradle/wrapper/gradle-wrapper.properties
Labels: android

#7863 Fix 5.x doc publishing
  .github/workflows/docs.yml
  okhttp/build.gradle.kts
Labels: documentation

#7847 Add a robolectric test to android-test
  gradle/libs.versions.toml
  okhttp-android/build.gradle.kts
  okhttp-android/src/test/kotlin/okhttp3/android/RobolectricClientBuilderTest.kt
Labels: android

#7864 Fix doc publishing
  okhttp/build.gradle.kts
Labels: documentation

#7866 Simplify generated source tasks
  okcurl/build.gradle.kts
  okhttp/build.gradle.kts
Labels: documentation

#7867 Attempt docs again
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  test_docs.sh
Labels: documentation

#7865 Run okhttp-android unit tests
  .github/workflows/build.yml
  okhttp-android/build.gradle.kts
  okhttp-android/src/androidTest/kotlin/okhttp3/android/AndroidAsyncDnsTest.kt
  okhttp-android/src/test/kotlin/okhttp3/android/RobolectricOkHttpClientTest.kt
Labels: android

#7871 Fix Android instrumentation tests on API 21
  okhttp-android/src/androidTest/kotlin/okhttp3/android/AndroidAsyncDnsTest.kt
  okhttp-android/src/main/kotlin/okhttp3/android/AndroidAsyncDns.kt
Labels: android
