Repository square/okhttp, pull requests merged in 2024-04, with the labels that each got.

#8242 Hide the value of sensitive query parameters in log
  okhttp-logging-interceptor/api/logging-interceptor.api
  okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
  okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.kt
Labels: android

#8290 Move RealCall and RealConnection to loom safe locks
  okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
  okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
  okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
Labels: loom

#8371 Move to centralised loom safe locks
  okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
  okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/Locks.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
  okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
  okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
  okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
  okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.kt
Labels: android, loom
