Repository square/okhttp, pull requests merged in 2025-05, with the labels that each got.

#8651 Create a friends configuration to use internals.
  android-test/build.gradle.kts
  build.gradle.kts
  mockwebserver-deprecated/build.gradle.kts
  mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/MockResponse.kt
  mockwebserver-junit4/build.gradle.kts
  mockwebserver-junit5/build.gradle.kts
  mockwebserver/build.gradle.kts
  mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt
  mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
  mockwebserver/src/test/java/mockwebserver3/RecordedRequestTest.kt
  okhttp-dnsoverhttps/build.gradle.kts
  okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
  okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsRecordCodecTest.kt
  okhttp-java-net-cookiejar/build.gradle.kts
  okhttp-java-net-cookiejar/src/main/kotlin/okhttp3/java/net/cookiejar/JavaNetCookieJar.kt
  okhttp-logging-interceptor/build.gradle.kts
  okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
  okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.kt
  okhttp-testing-support/build.gradle.kts
  okhttp-testing-support/src/main/kotlin/okhttp3/CallEvent.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/ConnectionEvent.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
  okhttp-testing-support/src/main/kotlin/okhttp3/internal/http/RecordingProxySelector.kt
  okhttp-tls/build.gradle.kts
  okhttp-tls/src/main/kotlin/okhttp3/tls/HandshakeCertificates.kt
  okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureExtendedTrustManager.kt
  okhttp-urlconnection/build.gradle.kts
  okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt
  samples/guide/build.gradle.kts
  samples/guide/src/main/java/okhttp3/recipes/kt/WiresharkExample.kt
  samples/guide/src/main/java/okhttp3/recipes/kt/YubikeyClientAuth.kt
  samples/slack/build.gradle.kts
  samples/static-server/build.gradle.kts
Labels: android

#8652 Cleanup github workflows add latest JDK
  .github/workflows/build.yml
  okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.kt
Labels: jdkversions

#8765 Fix test with latest JDKs
  mockwebserver-deprecated/src/test/java/okhttp3/mockwebserver/MockWebServerTest.kt
  mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
Labels: jdkversions

#8785 Remove JDK 8 ALPN runs of module-specific tests
  .github/workflows/build.yml
  build.gradle.kts
  okhttp/build.gradle.kts
  okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/Locks.kt
Labels: jdkversions

#8811 Fix native image tests' build
  native-image-tests/README.md
  native-image-tests/build.gradle.kts
Labels: graal

#8820 Run the loom tests on JDK 24
  .github/workflows/build.yml
Labels: loom
